name: maliek
favicon: null
layout_spectrum: 0.4874710899312049
typography_spectrum: 0.03612068318761885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3336121828760952
  lightness: 0.8703292079735547
  saturation: 0.8811741289682686
  rhythmicContrast: 0.6362844854593277
purpose: []
